/**
 * Chaînes par défaut (français) pour les apps Linux simulées.
 * Clés plates - surchargées par `content/strings.json` de la skin ou `CAPSULE_STRINGS_INLINE`.
 */
window.CAPSULE_STRINGS_DEFAULT = {
    'explorer.windowTitle': 'Fichiers',
    'firefox.windowTitle': 'Navigateur Web',
    'firefox.chromeAriaLabel': 'Interface navigateur',
    'firefox.tabsAriaLabel': 'Onglets',
    'firefox.tabNewLabel': 'Nouvel onglet',
    'firefox.tabNewButtonAria': 'Nouvel onglet',
    'firefox.toolbarAriaLabel': 'Barre de navigation',
    'firefox.backAria': 'Retour',
    'firefox.forwardAria': 'Avant',
    'firefox.reloadAria': 'Recharger',
    'firefox.addressLabel': 'Adresse',
    'firefox.addressPlaceholder': 'Rechercher avec Google ou saisir une adresse',
    'firefox.goAria': "Valider l'adresse",
    'firefox.goButton': 'Aller',
    'firefox.toolbarActionsAria': 'Actions navigateur',
    'firefox.homeAria': 'Accueil',
    'firefox.libraryAria': 'Bibliotheque',
    'firefox.bookmarksStarAria': 'Favoris',
    'firefox.menuAria': 'Menu',
    'firefox.bookmarksBarAria': 'Favoris',
    'firefox.bookmarkHome': 'Accueil',
    'firefox.bookmarkLocalhost': 'Localhost',
    'firefox.bookmarkLaCapsule': 'La Capsule',
    'firefox.bookmarkOsLaCapsule': 'os-lacapsule',
    'firefox.browserHomeLabel': 'CapsuleOS Navigateur',
    'firefox.shortcutsPanelAria': 'Raccourcis pedagogiques',
    'firefox.iframeOsLaCapsuleTitle': 'os-lacapsule',
    'firefox.homeTitle': 'Bienvenue',
    'firefox.homeLead':
        "Accueil simulation actif. Utilise le favori os-lacapsule pour afficher l'entree reelle du site.",
    'firefox.shortcutsPanelTitle': 'Raccourcis pedagogiques',
    'firefox.shortcutBlockHomeTitle': 'Accueil',
    'firefox.shortcutBlockHomeBody': "Cette vue sert de page d'accueil de la simulation du navigateur.",
    'firefox.shortcutBlockOsTitle': 'os-lacapsule',
    'firefox.shortcutBlockOsBody': 'Ce favori ouvre la page d\'entree reelle CapsuleOS dans le faux navigateur.',
    'firefox.shortcutBlockNavTitle': 'Navigation controlee',
    'firefox.shortcutBlockNavBody': 'Les autres entrees restent en mode simulation tant que non mappees.',
    'firefox.statusSimulation':
        'Mode simulation actif: la vue Accueil ouvre la page interne du navigateur.',
    'firefox.statusOsLaCapsuleLoading': 'Chargement de la page os-lacapsule...',
    'firefox.statusOsLaCapsuleShown': 'Page os-lacapsule affichee.',
    'firefox.statusSubmitRedirect': 'Toute saisie est redirigee vers os-lacapsule.',
    'firefox.statusHomeShown': 'Page Accueil affichee.',
    'firefox.statusHomeReloaded': 'Page Accueil rechargee.',
    'firefox.statusOsLaCapsuleReloaded': 'Page os-lacapsule rechargee.',
    'firefox.statusBackUnavailable': 'Retour indisponible pour le moment (mode simulation).',
    'firefox.statusForwardUnavailable': 'Avance indisponible pour le moment (mode simulation).',
    'firefox.statusNewTab': 'Nouvel onglet: page Accueil affichee.',
    'firefox.statusFavoriteHome': 'Favori "Accueil" ouvert.',
    'firefox.statusFavoriteOsLaCapsule': 'Favori « {label} » ouvert.',
    'firefox.statusBookmarkUnmapped': 'Favori « {label} » non mappe pour le moment.',
    'firefox.statusTabSimulated': 'Onglet « {label} » simule.',
    'firefox.statusErrorOsLaCapsule': "Erreur de chargement: impossible d'ouvrir la page os-lacapsule.",
    'mainMenu.userName': 'utilisateur',
    'mainMenu.searchPlaceholder': 'Rechercher...',
    'profile.windowTitle': 'À Propos',
    'librewriter.windowTitle': 'Sans nom 1 - LibreOffice Writer',
    'terminal.windowTitle': 'Terminal',
    'update_manager.windowTitle': 'Gestionnaire de mise à jour',
    'themes.windowTitle': 'Thèmes',
    'checklist.windowTitle': 'Missions',
    'checklist.description': 'Explore Linux Mint en accomplissant ces missions. Ta progression est sauvegardée.',
    'mainMenu.windowTitle': 'Menu',
    'visionneur_images.windowTitle': "Visionneur d'images",
    'visionneur_pdf.windowTitle': 'Visionneur PDF',
    'lecteur_multimedia.windowTitle': 'Lecteur multimédia'
};
