const fileSystem = {
    '/': {
        '/bin': {},
        '/home': {},
        '/media': {},
        '/proc': {},
        '/sbin': {},
        'swapfile': {},
        '/tmp': {},
        '/boot': {},
        '/dev': {},
        '/lib': {},
        '/libx32': {},
        '/lost+found': {},
        '/opt': {},
        '/run': {},
        '/srv': {},
        '/timeshift': {},
        '/var': {},
    },
    '/bin' : {
        'apt' : {},
        'apt-get' : {},
        'aptitude' : {},
        'apturl' : {},
        'cat' : {},
        'cinnamon' : {},
        'clear' : {},
        'crontab' : {},
        'curl' : {},
        'dd' : {},
        'dpkg' : {},
    },
    '/home': {
        '/user': {},
    },
    '/user': {
        '/Bureau': {},
        '/Documents': {},
        '/Images': {},
        '/Modèles': {},
        '/Musique': {},
        '/Public': {},
        '/Téléchargements': {},
        '/Vidéos': {},
    },
    '/media' : {
        '/disque amovible' : {},
    },
    '/proc' : {
        'diskstats' : {},
        'interrupts' : {},
        'kcore' : {},
        '/driver' : {},
        'locks' : {},
        'meminfo' : {},
        '/mounts' : {},
        '/net' : {},
        'partitions' : {},
        'swaps' : {},
    },
    '/sbin': {
        'add-apt-key' : {},
        'blkid' : {},
        'casper-login' : {},
        'chroot' : {},
        'cron' : {},
        'dmidcode' : {},
        'fdisk' : {},
        'grub-install' : {},
        'ifconfig' : {},
        'iptable' : {},
        'lvm' : {},
        'update-grub' : {},
        'wpa-cli' : {},
        'xfs-repair': {},
    },
    '/tmp': {
        'lavie.exe': {},
        'Emmanuel_Macron.pdf': {},
        'COVID-19.dll': {},
        'Windows11.bat': {},
        'trojan_au_secours': {},
    },
    '/usr': {
        '/bin': {},
        '/lib': {},
    },
};