/**
 * Chaînes par défaut (français) pour les apps Linux simulées.
 * Clés plates - surchargées par `content/strings.json` de la skin ou `CAPSULE_STRINGS_INLINE`.
 */
'use strict';
window.CAPSULE_STRINGS_DEFAULT = {
    'explorer.windowTitle': 'Fichiers',
    'firefox.windowTitle': 'Navigateur Web',
    'firefox.chromeAriaLabel': 'Interface navigateur',
    'firefox.tabsAriaLabel': 'Onglets',
    'firefox.tabNewLabel': 'Nouvel onglet',
    'firefox.tabNewButtonAria': 'Nouvel onglet',
    'firefox.toolbarAriaLabel': 'Barre de navigation',
    'firefox.backAria': 'Retour',
    'firefox.forwardAria': 'Avant',
    'firefox.reloadAria': 'Recharger',
    'firefox.addressLabel': 'Adresse',
    'firefox.addressPlaceholder': 'Rechercher avec Google ou saisir une adresse',
    'firefox.goAria': "Valider l'adresse",
    'firefox.goButton': 'Aller',
    'firefox.toolbarActionsAria': 'Actions navigateur',
    'firefox.homeAria': 'Accueil',
    'firefox.libraryAria': 'Bibliotheque',
    'firefox.bookmarksStarAria': 'Favoris',
    'firefox.menuAria': 'Menu',
    'firefox.profileAria': 'Profil Firefox',
    'firefox.pocketAria': 'Pocket',
    'firefox.bookmarkImportHint': 'Importer les marque-pages…',
    'firefox.newtabShortcutAliexpress': 'AliExpress',
    'firefox.newtabShortcutLeMonde': 'Le Monde',
    'firefox.newtabShortcutAdd': 'Ajouter un raccourci',
    'firefox.newtabShortcutAddAria': 'Ajouter un raccourci',
    'firefox.newtabSponsored': 'Sponsorisé',
    'firefox.newtabPocketTitle': 'Des articles qui font réfléchir',
    'firefox.newtabPocketArticle1Title': "InoCat, l'influenceuse sud-coréenne…",
    'firefox.newtabPocketArticle1Source': 'Madame Figaro',
    'firefox.newtabPocketArticle2Title': "Vassili Arkhipov, l'homme qui a sauvé l'humanité…",
    'firefox.newtabPocketArticle2Source': 'Le Point',
    'firefox.newtabPocketArticle3Title': '3 % de votre investissement reversés…',
    'firefox.newtabPocketArticle3Source': "Sponsorisé par CORUM L'Épargne",
    'firefox.statusProfileSoon': 'Profil Firefox : bientôt disponible.',
    'firefox.statusPocketSoon': 'Pocket : bientôt disponible.',
    'firefox.statusNewtabAddSoon': 'Ajout de raccourci : bientôt disponible.',
    'firefox.bookmarksBarAria': 'Favoris',
    'firefox.bookmarkHome': 'Accueil',
    'firefox.bookmarkImported': 'Importés',
    'firefox.bookmarkLocalhost': 'Localhost',
    'firefox.bookmarkLaCapsule': 'La Capsule',
    'firefox.bookmarkOsLaCapsule': 'os-lacapsule',
    'firefox.tabOsLaCapsuleLabel': 'La Capsule',
    'firefox.tabCloseAria': 'Fermer l’onglet',
    'firefox.newtabSearchLabel': 'Rechercher sur le Web',
    'firefox.newtabShortcutsAria': 'Raccourcis de la page d’accueil',
    'firefox.newtabShortcutWiki': 'Wikipédia',
    'firefox.newtabShortcutAmazon': 'Amazon',
    'firefox.newtabShortcutTemu': 'Temu',
    'firefox.newtabShortcutYoutube': 'YouTube',
    'firefox.newtabShortcutReddit': 'Reddit',
    'firefox.statusLibrarySoon': 'Bibliothèque : bientôt disponible.',
    'firefox.statusMenuSoon': 'Menu Firefox : bientôt disponible.',
    'firefox.statusMenuItem': 'Menu : {label}',
    'firefox.menuSyncHeader': 'Synchroniser et enregistrer les données',
    'firefox.menuSignIn': 'Connexion',
    'firefox.menuProfiles': 'Profils',
    'firefox.menuNewTab': 'Nouvel onglet',
    'firefox.menuNewWindow': 'Nouvelle fenêtre',
    'firefox.menuNewPrivateWindow': 'Nouvelle fenêtre privée',
    'firefox.menuBookmarksMenu': 'Marque-pages',
    'firefox.menuHistory': 'Historique',
    'firefox.menuDownloads': 'Téléchargements',
    'firefox.menuPasswords': 'Mots de passe',
    'firefox.menuAddons': 'Extensions et thèmes',
    'firefox.menuPrint': 'Imprimer...',
    'firefox.menuSavePage': 'Enregistrer sous...',
    'firefox.menuFind': 'Rechercher dans la page...',
    'firefox.menuTranslate': 'Traduire la page...',
    'firefox.menuZoomLabel': 'Zoom',
    'firefox.menuZoomOutAria': 'Réduire le zoom',
    'firefox.menuZoomInAria': 'Augmenter le zoom',
    'firefox.menuZoomFullscreenAria': 'Passer en plein écran',
    'firefox.menuSettings': 'Paramètres',
    'firefox.menuMoreTools': 'Outils supplémentaires',
    'firefox.menuReportSite': 'Signaler des problèmes avec ce site',
    'firefox.menuHelp': 'Aide',
    'firefox.menuBackAria': 'Retour',
    'firefox.menuProfilesNew': '➕ Nouveau profil',
    'firefox.menuProfilesManage': 'Gérer les profils',
    'firefox.menuBookmarkCurrentTab': 'Marquer l’onglet courant...',
    'firefox.menuBookmarksSearch': 'Rechercher dans les marque-pages',
    'firefox.menuBookmarksToggleBar': 'Masquer la barre personnelle',
    'firefox.menuBookmarksRecentSectionLabel': 'Marque-pages récents',
    'firefox.menuBookmarkDemoCustomize': 'Personnaliser Firefox',
    'firefox.menuBookmarkDemoContribute': 'Participer',
    'firefox.menuBookmarkDemoHelp': 'Obtenir de l’aide',
    'firefox.menuBookmarkDemoAbout': 'À propos de Mozilla',
    'firefox.menuBookmarksManage': 'Organiser les marque-pages',
    'firefox.menuHistoryRecentTabs': 'Onglets récemment fermés',
    'firefox.menuHistoryRecentWindows': 'Fenêtres récemment fermées',
    'firefox.menuHistorySearch': 'Rechercher dans l’historique',
    'firefox.menuHistoryRestoreSession': 'Restaurer la session précédente',
    'firefox.menuHistoryClear': 'Effacer l’historique récent...',
    'firefox.menuHistoryRecentSectionLabel': 'Historique récent',
    'firefox.menuHistoryDemo1': 'Compte Pro Intégré à votre Comptabilité',
    'firefox.menuHistoryDemo2': 'Google',
    'firefox.menuHistoryDemo3': 'about:newtab - Recherche Google',
    'firefox.menuHistoryDemo4': 'Google Search',
    'firefox.menuHistoryManage': 'Gérer l’historique',
    'firefox.menuToolsCustomizeToolbar': 'Personnaliser la barre d’outils...',
    'firefox.menuToolsSectionLabel': 'Outils du navigateur',
    'firefox.menuToolsDevtools': 'Outils de développement web',
    'firefox.menuToolsTaskManager': 'Gestionnaire de tâches',
    'firefox.menuToolsRemoteDebug': 'Débogage distant',
    'firefox.menuToolsBrowserConsole': 'Console du navigateur',
    'firefox.menuToolsResponsive': 'Vue adaptative',
    'firefox.menuToolsEyedropper': 'Pipette',
    'firefox.menuToolsViewSource': 'Code source de la page',
    'firefox.menuToolsDevExtensions': 'Extensions de développement',
    'firefox.menuHelpGetHelp': 'Obtenir de l’aide',
    'firefox.menuHelpFeedback': 'Partager des idées et des commentaires...',
    'firefox.menuHelpTroubleshootMode': 'Mode de dépannage...',
    'firefox.menuHelpTroubleshootInfo': 'Plus d’informations de dépannage',
    'firefox.menuHelpReportDeceptive': 'Signaler un site trompeur...',
    'firefox.menuHelpSwitchDevice': 'Passer à un nouvel appareil',
    'firefox.menuHelpAbout': 'À propos de Firefox',
    'firefox.statusReopenClosedTabEmpty': 'Aucun onglet fermé à restaurer.',
    'firefox.tabCtxNewRight': 'Nouvel onglet à droite',
    'firefox.tabCtxNewGroup': 'Ajouter l’onglet à un nouveau groupe',
    'firefox.tabCtxReload': 'Recharger l’onglet',
    'firefox.tabCtxMute': 'Couper le son de l’onglet',
    'firefox.tabCtxPin': 'Épingler l’onglet',
    'firefox.tabCtxUnload': 'Décharger l’onglet',
    'firefox.tabCtxDuplicate': 'Dupliquer l’onglet',
    'firefox.tabCtxAiChatbot': 'Demander à un chatbot IA (Z)',
    'firefox.tabCtxBookmark': 'Marquer l’onglet...',
    'firefox.tabCtxMove': 'Déplacer l’onglet',
    'firefox.tabCtxSelectAll': 'Sélectionner tous les onglets',
    'firefox.tabCtxClose': 'Fermer l’onglet',
    'firefox.tabCtxCloseDuplicates': 'Fermer les onglets en double',
    'firefox.tabCtxCloseMultiple': 'Fermer plusieurs onglets',
    'firefox.tabCtxReopenClosed': 'Rouvrir l’onglet fermé',
    'firefox.tooltipBackLine1': 'Reculer d’une page (Alt+Flèche gauche)',
    'firefox.tooltipBackLine2': 'Faire un clic droit ou cliquer en déplaçant la souris vers le bas pour afficher l’historique',
    'firefox.tooltipForward': 'Suivant (Alt+Flèche droite)',
    'firefox.tooltipReload': 'Actualiser la page courante (Ctrl+R)',
    'firefox.tooltipHamburger': 'Ouvrir le menu de l’application',
    'firefox.tooltipProfile': 'Compte',
    'firefox.findbarPlaceholder': 'Saisir...',
    'firefox.findbarPrevAria': 'Précédent',
    'firefox.findbarNextAria': 'Suivant',
    'firefox.findbarHighlightAll': 'Tout surligner',
    'firefox.findbarMatchCase': 'Respecter la casse',
    'firefox.findbarMatchDiacritics': 'Respecter les diacritiques',
    'firefox.findbarWholeWord': 'Mots entiers',
    'firefox.findbarCloseAria': 'Fermer',
    'firefox.findbarNotFound': 'Texte non trouvé',
    'firefox.findbarCount': '{current} sur {total}',
    'firefox.bookmarkCtxOpen': 'Ouvrir',
    'firefox.bookmarkCtxOpenNewTab': 'Ouvrir dans un nouvel onglet',
    'firefox.bookmarkCtxOpenNewWindow': 'Ouvrir dans une nouvelle fenêtre',
    'firefox.bookmarkCtxEdit': 'Modifier le marque-page...',
    'firefox.bookmarkCtxCopy': 'Copier l’emplacement',
    'firefox.bookmarkCtxDelete': 'Supprimer',
    'firefox.bookmarkCtxAddPage': 'Ajouter cette page...',
    'firefox.bookmarkCtxNewFolder': 'Nouveau dossier...',
    'firefox.bookmarkCtxNewSeparator': 'Nouvelle séparation',
    'firefox.bookmarkCtxShowSidebar': 'Afficher les marque-pages dans la barre latérale',
    'firefox.pageCtxSelectAll': 'Tout sélectionner',
    'firefox.pageCtxViewSource': 'Afficher le code source de la page',
    'firefox.pageCtxPageInfo': 'Informations sur la page',
    'firefox.pageCtxInspectA11y': 'Inspecter les propriétés d’accessibilité',
    'firefox.linkCtxOpen': 'Ouvrir le lien',
    'firefox.linkCtxOpenNewTab': 'Ouvrir le lien dans un nouvel onglet',
    'firefox.linkCtxOpenNewWindow': 'Ouvrir le lien dans une nouvelle fenêtre',
    'firefox.linkCtxOpenPrivate': 'Ouvrir le lien dans une fenêtre de navigation privée',
    'firefox.linkCtxSaveAs': 'Enregistrer le lien sous...',
    'firefox.linkCtxCopyAddress': 'Copier l’adresse du lien',
    'firefox.linkCtxCopyNoTrack': 'Copier le lien sans suivi',
    'firefox.linkCtxInspect': 'Inspecter',
    'firefox.selectionCtxCopy': 'Copier',
    'firefox.selectionCtxSelectAll': 'Tout sélectionner',
    'firefox.selectionCtxSearchWeb': 'Rechercher dans le Web',
    'firefox.selectionCtxSearchWebText': 'Rechercher « {text} » dans le Web',
    'firefox.selectionCtxSearchWith': 'Rechercher avec...',
    'firefox.selectionCtxSearchWithText': 'Rechercher « {text} » avec...',
    'firefox.selectionCtxTranslate': 'Traduire la sélection',
    'firefox.selectionCtxSaveAs': 'Enregistrer la sélection sous...',
    'firefox.selectionCtxSendEmail': 'Envoyer le lien par e-mail',
    'firefox.selectionCtxInspect': 'Inspecter',
    'firefox.statusSelectionCopied': 'Sélection copiée.',
    'firefox.prefsTabLabel': 'Paramètres',
    'firefox.prefsTopSearch': 'Rechercher dans les paramètres',
    'firefox.prefsSectionGeneral': 'Général',
    'firefox.prefsSectionHome': 'Accueil',
    'firefox.prefsSectionSearch': 'Recherche',
    'firefox.prefsSectionPrivacy': 'Vie privée et sécurité',
    'firefox.prefsSectionSync': 'Synchronisation',
    'firefox.prefsSectionLabs': 'Firefox Labs',
    'firefox.prefsSectionOtherProducts': 'Autres produits de Mozilla',
    'firefox.prefsSectionAddons': 'Extensions et thèmes',
    'firefox.prefsSectionHelp': 'Assistance de Firefox',
    'firefox.prefsSectionComingSoon': 'Cette section sera complétée dans une prochaine passe.',
    'firefox.statusPrefChanged': 'Préférence « {label} » : {state}.',
    'firefox.prefsStateOn': 'activé',
    'firefox.prefsStateOff': 'désactivé',
    'firefox.prefsGeneralStartup': 'Démarrage',
    'firefox.prefsStartupReopen': 'Ouvrir les fenêtres et onglets précédents',
    'firefox.prefsStartupCheckDefault': 'Toujours vérifier que Firefox est votre navigateur par défaut',
    'firefox.prefsStartupIsDefault': 'Firefox est votre navigateur par défaut',
    'firefox.prefsGeneralTabs': 'Onglets',
    'firefox.prefsTabsCtrlTab': 'Ctrl+Tab fait défiler vos onglets en les classant selon leur dernière utilisation',
    'firefox.prefsTabsOpenLinksInTabs': 'Ouvrir les liens dans les onglets au lieu de nouvelles fenêtres',
    'firefox.prefsTabsOpenFromApps': 'Ouvrir les liens provenant d’applications à côté de l’onglet que vous consultez',
    'firefox.prefsTabsSwitchImmediately': 'À l’ouverture d’un lien, d’une image ou d’un média dans un nouvel onglet, basculer vers celui-ci immédiatement',
    'firefox.prefsTabsWarnClose': 'Me demander avant de fermer plusieurs onglets',
    'firefox.prefsTabsWarnQuit': 'Me demander avant de quitter avec Ctrl+Q',
    'firefox.prefsTabsHoverPreview': 'Afficher un aperçu au survol des onglets',
    'firefox.prefsGeneralImport': 'Importer des données d’un navigateur',
    'firefox.prefsGeneralProfiles': 'Profils',
    'firefox.prefsGeneralLayout': 'Disposition du navigateur',
    'firefox.prefsGeneralLanguageAppearance': 'Langue et apparence',
    'firefox.prefsGeneralFonts': 'Polices',
    'firefox.prefsGeneralZoom': 'Zoom',
    'firefox.prefsGeneralLanguage': 'Langue',
    'firefox.prefsGeneralDownloads': 'Téléchargements',
    'firefox.prefsGeneralApplications': 'Applications',
    'firefox.prefsImportDesc': 'Importer les marques-pages, les mots de passe, l’historique et les données de remplissage automatique dans Firefox',
    'firefox.prefsImportBtn': 'Importer des données',
    'firefox.prefsProfilesDesc': 'Chaque profil dispose de données de navigation et de paramètres distincts, comme l’historique, les mots de passe, etc. En savoir plus',
    'firefox.prefsProfilesBtn': 'Gérer les profils',
    'firefox.prefsLayoutHorizontal': 'Onglets horizontaux',
    'firefox.prefsLayoutHorizontalDesc': 'Onglets affichés en haut du navigateur',
    'firefox.prefsLayoutVertical': 'Onglets verticaux',
    'firefox.prefsLayoutVerticalDesc': 'Onglets affichés sur le côté, dans le panneau latéral',
    'firefox.prefsLayoutSidebar': 'Afficher le panneau latéral',
    'firefox.prefsLayoutSidebarDesc': 'Accédez rapidement aux marque-pages, aux onglets de votre téléphone, aux chatbots IA et encore plus sans quitter l’affichage principal.',
    'firefox.prefsWebAppearance': 'Apparence des sites web',
    'firefox.prefsWebAppearanceDesc': 'Certains sites web adaptent leur jeu de couleurs en fonction de vos préférences. Choisissez le jeu de couleurs que vous souhaitez utiliser pour ces sites.',
    'firefox.prefsWebAppearanceAuto': 'Automatique',
    'firefox.prefsWebAppearanceLight': 'Clair',
    'firefox.prefsWebAppearanceDark': 'Sombre',
    'firefox.prefsContrastControl': 'Contrôle du contraste',
    'firefox.prefsContrastControlDesc': 'Les sites web utilisent beaucoup de couleurs différentes pour le premier plan et l’arrière-plan. Configurez Firefox pour qu’il utilise les mêmes couleurs sur tous les sites web afin d’améliorer leur lisibilité.',
    'firefox.prefsContrastAuto': 'Automatique (utiliser les paramètres système)',
    'firefox.prefsContrastOff': 'Désactivé',
    'firefox.prefsContrastCustom': 'Personnalisé',
    'firefox.prefsContrastCustomBtn': 'Gérer les couleurs...',
    'firefox.prefsFontsDefault': 'Police par défaut',
    'firefox.prefsFontsDefaultValue': 'Par défaut (Noto Serif)',
    'firefox.prefsFontsAdvanced': 'Avancé...',
    'firefox.prefsZoomDefault': 'Zoom par défaut',
    'firefox.prefsZoomTextOnly': 'Agrandir uniquement le texte',
    'firefox.prefsLanguageDesc': 'Choisissez en quelle langue doivent s’afficher les menus, messages et notifications de Firefox.',
    'firefox.prefsLanguageAlt': 'Choisir des alternatives...',
    'firefox.prefsLanguageWebPages': 'Choix de la langue préférée pour l’affichage des pages',
    'firefox.prefsChooseBtn': 'Choisir...',
    'firefox.prefsLanguageOsFormat': 'Utiliser les paramètres de votre système d’exploitation en « Français (France) » pour formater les dates, les heures, les nombres et les mesures.',
    'firefox.prefsDownloadsFolder': 'Téléchargements',
    'firefox.prefsBrowseBtn': 'Parcourir...',
    'firefox.prefsDownloadsAskWhere': 'Toujours demander où enregistrer les fichiers',
    'firefox.prefsDownloadsDeletePrivate': 'Supprimer les fichiers téléchargés en navigation privée quand toutes les fenêtres de navigation privée sont fermées',
    'firefox.prefsApplicationsDesc': 'Définissez le comportement de Firefox avec les fichiers que vous téléchargez et les applications que vous utilisez lorsque vous naviguez.',
    'firefox.prefsAppActionSave': 'Enregistrer le fichier',
    'firefox.prefsAppTypeAvif': 'Fichier image AV1 (AVIF)',
    'firefox.prefsAppActionOpenFirefox': 'Ouvrir dans Firefox',
    'firefox.prefsAppTypeWebp': 'Image WebP',
    'firefox.prefsAppActionThunderbird': 'Utiliser Messagerie Thunderbird (par défaut)',
    'firefox.prefsAppTypePdf': 'Portable Document Format (PDF)',
    'firefox.prefsAppTypeSvg': 'Scalable Vector Graphics (SVG)',
    'firefox.prefsHomeNewWindows': 'Nouvelles fenêtres et nouveaux onglets',
    'firefox.prefsHomeNewWindowsDesc': 'Choisissez ce qui est affiché lorsque vous ouvrez votre page d’accueil, de nouvelles fenêtres ou de nouveaux onglets.',
    'firefox.prefsHomeAndWindows': 'Page d’accueil et nouvelles fenêtres',
    'firefox.prefsHomeDefaultValue': 'Page d’accueil de Firefox (par défaut)',
    'firefox.prefsHomeNewTabs': 'Nouveaux onglets',
    'firefox.prefsHomeContent': 'Contenu de la Page d’accueil de Firefox',
    'firefox.prefsHomeContentDesc': 'Choisissez le contenu que vous souhaitez pour la Page d’accueil de Firefox.',
    'firefox.prefsHomeWebSearch': 'Recherche web',
    'firefox.prefsHomeShortcuts': 'Raccourcis',
    'firefox.prefsHomeShortcutsSub': 'Sites que vous enregistrez ou visitez',
    'firefox.prefsHomeRecommended': 'Articles recommandés',
    'firefox.prefsHomeRecommendedSub': 'Contenu exceptionnel sélectionné par les membres de la gamme de produits Firefox',
    'firefox.prefsHomeSupport': 'Soutenir Firefox',
    'firefox.prefsHomeSponsoredShortcuts': 'Raccourcis sponsorisés',
    'firefox.prefsHomeSponsoredArticles': 'Articles sponsorisés',
    'firefox.prefsHomeRecentActivity': 'Activité récente',
    'firefox.prefsHomeRecentActivitySub': 'Une sélection de sites et de contenus récents',
    'firefox.prefsHomeVisitedPages': 'Pages visitées',
    'firefox.prefsHomeBookmarks2': 'Marque-pages',
    'firefox.prefsHomeLastDownload': 'Dernier téléchargement',
    'firefox.prefsSearchDefaultEngine': 'Moteur de recherche par défaut',
    'firefox.prefsSearchDefaultEngineDesc': 'Ceci est votre moteur de recherche par défaut dans la barre d’adresse et la barre de recherche. Vous pouvez le changer à tout moment.',
    'firefox.prefsSearchShowTerms': 'Afficher les termes des recherches dans la barre d’adresse des pages de résultats',
    'firefox.prefsSearchSuggestions': 'Suggestions de recherche',
    'firefox.prefsSearchSuggestionsDesc': 'Choisissez comment apparaîtront les suggestions des moteurs de recherche.',
    'firefox.prefsSearchShowSuggestions': 'Afficher les suggestions de recherche',
    'firefox.prefsSearchSuggestionsBeforeHistory': 'Afficher les suggestions de recherche avant l’historique de navigation dans les résultats de la barre d’adresse',
    'firefox.prefsSearchSuggestionsPrivate': 'Afficher les suggestions de recherche dans les fenêtres de navigation privée',
    'firefox.prefsSearchSuggestionsPopular': 'Afficher les suggestions de recherche populaires',
    'firefox.prefsSearchRecent': 'Afficher les recherches récentes',
    'firefox.prefsSearchFirefoxSuggests': 'Firefox suggère',
    'firefox.prefsSearchFirefoxSuggestsDesc': 'Des suggestions de Firefox et de nos partenaires dans votre barre d’adresse. En savoir plus',
    'firefox.prefsSearchHistory': 'Historique de navigation',
    'firefox.prefsSearchBookmarksItem': 'Marque-pages',
    'firefox.prefsSearchOpenTabs': 'Onglets ouverts',
    'firefox.prefsSearchShortcutsItem': 'Raccourcis',
    'firefox.prefsSearchSuggestEngines': 'Suggérer des moteurs de recherche à utiliser',
    'firefox.prefsSearchQuickActions': 'Actions rapides',
    'firefox.prefsSearchFirefoxSuggestions': 'Suggestions de Firefox',
    'firefox.prefsSearchFirefoxSuggestionsSub': 'Obtenir des suggestions du Web en rapport avec votre recherche.',
    'firefox.prefsSearchSponsoredSuggestions': 'Suggestions de sponsors',
    'firefox.prefsSearchSponsoredSuggestionsSub': 'Soutenez Firefox en affichant de temps en temps des suggestions sponsorisées.',
    'firefox.prefsSearchRejected': 'Suggestions rejetées — Restaurer les suggestions rejetées des sponsors et de Firefox.',
    'firefox.prefsRestoreBtn': 'Restaurer',
    'firefox.prefsSearchShortcutsTitle': 'Raccourcis de recherche',
    'firefox.prefsSearchShortcutsDesc': 'Sélectionnez les moteurs de recherche alternatifs qui apparaissent sous la barre d’adresse et la barre de recherche lorsque vous commencez à saisir un mot-clé.',
    'firefox.prefsWikipediaFr': 'Wikipédia (fr)',
    'firefox.prefsSearchOpenTabs2': 'Onglets',
    'firefox.prefsSearchHistoryItem': 'Historique',
    'firefox.prefsSearchActionsItem': 'Actions',
    'firefox.prefsPrivacyTracking': 'Protection renforcée contre le pistage',
    'firefox.prefsPrivacyTrackingIntro': 'Les traqueurs vous suivent en ligne pour collecter des informations sur vos habitudes de navigation et vos centres d’intérêt. Firefox bloque un grand nombre de ces traqueurs et de scripts malveillants. En savoir plus',
    'firefox.prefsPrivacyStandard': 'Standard',
    'firefox.prefsPrivacyStandardDesc': 'Équilibré entre protection et performances. Les pages se chargeront normalement.',
    'firefox.prefsPrivacyStrict': 'Stricte',
    'firefox.prefsPrivacyStrictDesc': 'Protection renforcée, mais certains sites ou contenus peuvent ne pas fonctionner correctement.',
    'firefox.prefsPrivacyCustom': 'Personnalisée',
    'firefox.prefsPrivacyCustomDesc': 'Choisissez les traqueurs et les scripts à bloquer.',
    'firefox.prefsPrivacyCookieProtection': 'Inclut la protection totale contre les cookies, notre fonctionnalité de protection de la vie privée la plus puissante',
    'firefox.prefsManageExceptions': 'Gérer les exceptions...',
    'firefox.prefsPrivacyWebsitePrefs': 'Préférences de confidentialité des sites web',
    'firefox.prefsPrivacyDoNotSell': 'Demander aux sites web de ne pas vendre ni partager mes données',
    'firefox.prefsPrivacyCookies': 'Cookies et données de sites',
    'firefox.prefsClearData': '🔥 Effacer les données de navigation',
    'firefox.prefsCookiesDiskUsage': 'Le stockage des cookies, de l’historique, des données de sites et du cache utilise actuellement 105 Mo d’espace disque.',
    'firefox.prefsManageBrowsingData': 'Gérer les données de navigation',
    'firefox.prefsManageExceptionsTitle': 'Vous pouvez spécifier quels sites web sont toujours ou jamais autorisés à utiliser des cookies et des données de site.',
    'firefox.prefsCookiesDeleteOnClose': 'Supprimer les cookies et les données des sites à la fermeture de Firefox',
    'firefox.prefsPrivacyPasswords': 'Mots de passe',
    'firefox.prefsPasswordsOffer': 'Proposer d’enregistrer les mots de passe',
    'firefox.prefsExceptionsBtn': 'Exceptions...',
    'firefox.prefsPasswordsAutofill': 'Remplir automatiquement les noms d’utilisateur et mots de passe',
    'firefox.prefsPasswordsSuggest': 'Suggérer des mots de passe compliqués...',
    'firefox.prefsPasswordsRelay': 'Proposer des alias de messagerie Firefox Relay pour protéger votre adresse e-mail',
    'firefox.prefsPasswordsBreachAlerts': 'Afficher des alertes pour les mots de passe de sites concernés par des fuites de données',
    'firefox.prefsPasswordsPrimary': 'Utiliser un mot de passe principal',
    'firefox.prefsChangePrimaryPassword': 'Changer le mot de passe principal...',
    'firefox.prefsPrivacyPayments': 'Moyens de paiement',
    'firefox.prefsPaymentsAutofill': 'Enregistrer et renseigner automatiquement les informations de paiement',
    'firefox.prefsManagePayments': 'Gérer les moyens de paiement',
    'firefox.prefsPrivacyAddresses': 'Adresses et autres informations',
    'firefox.prefsAddressesAutofill': 'Enregistrer et remplir automatiquement les adresses',
    'firefox.prefsManageAddresses': 'Gérer les adresses et les autres informations',
    'firefox.prefsPrivacyHistory': 'Historique',
    'firefox.prefsHistoryRetention': 'Règles de conservation',
    'firefox.prefsHistoryKeep': 'Conserver l’historique',
    'firefox.prefsHistoryClearBtn': 'Effacer l’historique...',
    'firefox.prefsHistoryInfoText': 'Firefox conservera les données de navigation, les téléchargements, les formulaires et l’historique de recherche.',
    'firefox.prefsPrivacyPermissions': 'Permissions',
    'firefox.prefsPermLocation': 'Localisation',
    'firefox.prefsSettingsBtn': 'Paramètres...',
    'firefox.prefsPermCamera': 'Caméra',
    'firefox.prefsPermMicrophone': 'Microphone',
    'firefox.prefsPermSpeaker': 'Sélection du haut-parleur',
    'firefox.prefsPermNotifications': 'Notifications',
    'firefox.prefsPermAutoplay': 'Lecture automatique',
    'firefox.prefsPermVr': 'Réalité virtuelle',
    'firefox.prefsPermBlockPopups': 'Bloquer les popups et les redirections tierces',
    'firefox.prefsPermWarnAddons': 'Prévenir lorsque les sites essaient d’installer des modules complémentaires',
    'firefox.prefsPrivacyDataCollection': 'Collecte de données par Firefox et utilisation',
    'firefox.prefsPrivacyDataCollectionDesc': 'Nous nous efforçons de vous laisser le choix et de ne recueillir que le minimum de données nécessaires à l’amélioration de Firefox pour tout le monde. Consulter la politique de confidentialité',
    'firefox.prefsDataTechnical': 'Envoyer des données techniques et d’interaction à Mozilla',
    'firefox.prefsDataTechnicalDesc': 'Ce partage nous aide à améliorer les fonctionnalités, les performances et la stabilité de Firefox.',
    'firefox.prefsDataPersonalized': 'Autoriser les recommandations personnalisées d’extensions',
    'firefox.prefsDataPersonalizedDesc': 'Recevez des recommandations d’extensions pour améliorer votre navigation.',
    'firefox.prefsDataStudies': 'Installer et lancer des études',
    'firefox.prefsDataStudiesDesc': 'Testez des fonctionnalités et des idées avant qu’elles ne soient disponibles pour tout le monde.',
    'firefox.prefsDataPing': 'Envoyer un ping quotidien d’utilisation à Mozilla',
    'firefox.prefsDataPingDesc': 'Ce paramètre aide Mozilla à évaluer le nombre d’utilisateurs actifs.',
    'firefox.prefsDataCrashReports': 'Envoyer automatiquement les rapports de plantage',
    'firefox.prefsDataCrashReportsDesc': 'Les rapports de plantage permettent à Mozilla de diagnostiquer et de corriger des problèmes avec le navigateur. Les rapports peuvent contenir des données personnelles ou sensibles.',
    'firefox.prefsPrivacySecurity': 'Sécurité',
    'firefox.prefsSecurityBlockDangerous': 'Bloquer les contenus dangereux ou trompeurs',
    'firefox.prefsSecurityBlockDownloads': 'Bloquer les téléchargements dangereux',
    'firefox.prefsSecurityReportUnwanted': 'Signaler la présence de logiciels indésirables ou peu communs',
    'firefox.prefsPrivacyCertificates': 'Certificats',
    'firefox.prefsCertificatesDesc': 'Configurer les certificats que Firefox utilise pour l’authentification. En savoir plus',
    'firefox.prefsShowCertificates': 'Afficher les certificats...',
    'firefox.prefsSecurityDevices': 'Périphériques de sécurité...',
    'firefox.prefsPrivacyHttps': 'Mode HTTPS uniquement',
    'firefox.prefsHttpsDesc': 'Ce mode autorise seulement les connexions sécurisées aux sites web. Firefox demande avant d’établir une connexion non sécurisée. En savoir plus',
    'firefox.prefsHttpsAll': 'Activer le mode HTTPS uniquement dans toutes les fenêtres',
    'firefox.prefsHttpsPrivate': 'Activer le mode HTTPS uniquement dans les fenêtres privées seulement',
    'firefox.prefsHttpsOff': 'Ne pas activer le mode HTTPS uniquement',
    'firefox.prefsHttpsOffDesc': 'Firefox peut tout de même surclasser certaines connexions',
    'firefox.prefsSyncHeadline': 'Emportez votre Web partout avec vous',
    'firefox.prefsSyncDesc': 'Synchronisez marque-pages, historique, onglets, mots de passe, modules complémentaires et paramètres entre tous vos appareils.',
    'firefox.prefsSyncSignIn': 'Se connecter pour synchroniser...',
    'firefox.prefsLabsIntro': 'Essayez nos fonctionnalités expérimentales ! Elles sont en cours de développement et évoluent, ce qui peut avoir un effet sur le fonctionnement de Firefox.',
    'firefox.prefsLabsCustomize': 'Personnalisez votre navigation',
    'firefox.prefsLabsIme': 'Barre d’adresse : afficher les résultats pendant la composition IME',
    'firefox.prefsLabsImeDesc': 'Un IME (Input Method Editor, éditeur de méthode de saisie) est un outil qui permet la saisie de symboles complexes. Activer cette expérience conserve ouvert le panneau de la barre d’adresse pendant que l’IME est utilisé pour saisir du texte.',
    'firefox.panelHistoryTitle': 'Historique',
    'firefox.panelDownloadsTitle': 'Téléchargements',
    'firefox.panelCloseAria': 'Fermer le panneau',
    'firefox.historyEmpty': 'Aucune entrée dans l’historique de session.',
    'firefox.downloadDemoName': 'guide-capsuleos-simulation.pdf',
    'firefox.downloadDemoSize': '248 Ko',
    'firefox.tabSearchLabel': 'Recherche : {query}',
    'firefox.tabSearchDefault': 'Recherche Google',
    'firefox.statusNewtabShortcutSoon': 'Raccourci « {label} » : bientôt disponible.',
    'firefox.statusOsLaCapsuleLoading': 'Chargement de la page os-lacapsule...',
    'firefox.statusOsLaCapsuleShown': 'Page os-lacapsule affichee.',
    'firefox.statusWebLoading': 'Chargement de la page…',
    'firefox.statusWebShown': 'Page affichée.',
    'firefox.statusWebReloaded': 'Page rechargée.',
    'firefox.statusMntOpen': 'Ouverture du module pédagogique « {label} »…',
    'firefox.mntPanelLead': 'Module pédagogique « {module} » — parcours monté sous /mnt.',
    'firefox.mntPanelHint': 'Les Missions et les applications du scénario s\'ouvrent automatiquement si disponibles sur ce bureau.',
    'firefox.statusErrorWeb': "Erreur de chargement : impossible d'ouvrir la page.",
    'firefox.iframeOsLaCapsuleTitle': 'os-lacapsule',
    'firefox.statusSubmitRedirect': 'Toute saisie est redirigee vers os-lacapsule.',
    'firefox.statusHomeShown': 'Page Accueil affichee.',
    'firefox.statusHomeReloaded': 'Page Accueil rechargee.',
    'firefox.statusOsLaCapsuleReloaded': 'Page os-lacapsule rechargee.',
    'firefox.statusBackUnavailable': 'Retour indisponible pour le moment (mode simulation).',
    'firefox.statusForwardUnavailable': 'Avance indisponible pour le moment (mode simulation).',
    'firefox.statusNewTab': 'Nouvel onglet: page Accueil affichee.',
    'firefox.statusFavoriteHome': 'Favori "Accueil" ouvert.',
    'firefox.statusFavoriteOsLaCapsule': 'Favori « {label} » ouvert.',
    'firefox.statusBookmarkUnmapped': 'Favori « {label} » non mappe pour le moment.',
    'firefox.statusTabSimulated': 'Onglet « {label} » simule.',
    'firefox.statusErrorOsLaCapsule': "Erreur de chargement: impossible d'ouvrir la page os-lacapsule.",
    'firefox.siteLinuxMintTitle': 'Linux Mint',
    'firefox.siteLinuxMintLead': 'From freedom came elegance — linuxmint.com',
    'mainMenu.userName': 'capsule',
    'mainMenu.searchPlaceholder': 'Rechercher...',
    'profile.windowTitle': 'À Propos',
    'librewriter.windowTitle': 'Sans nom 1 - LibreOffice Writer',
    'librecalc.windowTitle': 'Sans nom 1 - LibreOffice Calc',
    'terminal.windowTitle': 'Terminal',
    'update_manager.windowTitle': 'Gestionnaire de mise à jour',
    'mintinstall.windowTitle': 'Logithèque',
    'system_monitor.windowTitle': 'Moniteur système',
    'baobab.windowTitle': 'Analyseur d\'espace disque',
    'webapp_manager.windowTitle': 'Applications Web',
    'sticky.windowTitle': 'Notes',
    'warpinator.windowTitle': 'Warpinator',
    'hypnotix.windowTitle': 'Hypnotix',
    'transmission.windowTitle': 'Transmission',
    'mintbackup.windowTitle': 'Outil de sauvegarde',
    'bulky.windowTitle': 'Renommer fichiers',
    'timeshift.windowTitle': 'Timeshift',
    'thunderbird.windowTitle': 'Thunderbird',
    'mintwelcome.windowTitle': 'Écran d\'accueil Mint',
    'gucharmap.windowTitle': 'Table de caractères',
    'simple_scan.windowTitle': 'Numérisation de documents',
    'thingy.windowTitle': 'Bibliothèque',
    'rhythmbox.windowTitle': 'Rhythmbox',
    'gnome_disks.windowTitle': 'Disques',
    'libreoffice_startcenter.windowTitle': 'LibreOffice',
    'libreoffice_draw.windowTitle': 'Sans nom 1 — LibreOffice Draw',
    'libreoffice_impress.windowTitle': 'Sans nom 1 — LibreOffice Impress',
    'mintstick.windowTitle': 'Créateur de clé USB',
    'mintstick_format.windowTitle': 'Formateur de clé USB',
    'font_viewer.windowTitle': 'Polices',
    'power_stats.windowTitle': 'Statistiques d\'alimentation',
    'mate_color_select.windowTitle': 'Sélecteur de couleur',
    'themes.windowTitle': 'Thèmes',
    'checklist.windowTitle': 'Missions',
    'checklist.description': 'Explore Linux Mint en accomplissant ces missions. Ta progression est sauvegardée.',
    'checklist.hint.open-nemo': 'Lance Nemo depuis la barre des tâches',
    'checklist.hint.open-menu': 'Clique sur le logo Mint en bas à gauche',
    'checklist.hint.open-profile': 'Ouvre le profil Linux Mint',
    'mainMenu.windowTitle': 'Menu',
    'visionneur_images.windowTitle': "Visionneur d'images",
    'visionneur_pdf.windowTitle': 'Visionneur PDF',
    'lecteur_multimedia.windowTitle': 'Lecteur multimédia',
    'calculator.windowTitle': 'Calculatrice',
    'screenshot.windowTitle': 'Capture d\'écran',
    'drawing.windowTitle': 'Sans titre — Dessin',
    'file_roller.windowTitle': 'Gestionnaire d\'archives',
    'mintdrivers.windowTitle': 'Gestionnaire de pilotes',
    'mintdrivers.lookingTitle': 'Recherche de pilotes',
    'mintdrivers.waitHint': 'Veuillez patienter…',
    'mintdrivers.noDriversTitle': 'Aucun pilote nécessaire',
    'mintdrivers.noDriversBody': 'Votre ordinateur n\'a besoin d\'aucun pilote supplémentaire.',
    'text_editor.windowTitle': 'Éditeur de texte',
    'clocks.windowTitle': 'Horloges',
    'calendar.windowTitle': 'Calendrier',
    'firefox.devtoolsTabInspector': 'Inspecteur',
    'firefox.devtoolsTabConsole': 'Console',
    'firefox.devtoolsTabDebugger': 'Débogueur',
    'firefox.devtoolsTabNetwork': 'Réseau',
    'firefox.devtoolsTabStyleEditor': 'Éditeur de style',
    'firefox.devtoolsTabPerformance': 'Performances',
    'firefox.devtoolsTabMemory': 'Mémoire',
    'firefox.devtoolsTabStorage': 'Stockage',
    'firefox.devtoolsTabAccessibility': 'Accessibilité',
    'firefox.devtoolsTabApplications': 'Applications',
    'firefox.devtoolsInspectorHtmlTree': 'Arborescence HTML',
    'firefox.devtoolsInspectorSearch': 'Rechercher dans le HTML',
    'firefox.devtoolsInspectorHint': 'Survolez ou cliquez un élément de la page pour l’inspecter.',
    'firefox.devtoolsInspectorCssRules': 'Règles CSS',
    'firefox.devtoolsInspectorFilterStyles': 'Filtrer les styles',
    'firefox.devtoolsInspectorNoSelection': 'Aucun élément sélectionné.',
    'firefox.devtoolsInspectorLayout': 'Mise en page',
    'firefox.devtoolsInspectorComputed': 'Calculé',
    'firefox.devtoolsInspectorChanges': 'Modifications',
    'firefox.devtoolsInspectorCompat': 'Compatibilité',
    'firefox.devtoolsInspectorFlexHint': 'Sélectionnez un conteneur flexible ou un élément flex pour continuer',
    'firefox.devtoolsConsoleFilter': 'Filtrer',
    'firefox.devtoolsConsoleErrors': 'Erreurs',
    'firefox.devtoolsConsoleWarnings': 'Avertissements',
    'firefox.devtoolsConsoleInfo': 'Informations',
    'firefox.devtoolsConsoleLogs': 'Journaux',
    'firefox.devtoolsConsolePlaceholder': 'Saisir une expression JavaScript…',
    'firefox.devtoolsDebuggerSources': 'Sources',
    'firefox.devtoolsDebuggerOutline': 'Structure',
    'firefox.devtoolsDebuggerSearch': 'Rechercher',
    'firefox.devtoolsDebuggerGoToFile': 'Aller au fichier',
    'firefox.devtoolsDebuggerSearchFiles': 'Rechercher dans des fichiers',
    'firefox.devtoolsDebuggerAllShortcuts': 'Afficher tous les raccourcis',
    'firefox.devtoolsDebuggerWatch': 'Expressions espionnes',
    'firefox.devtoolsDebuggerBreakpoints': 'Points d’arrêt',
    'firefox.devtoolsDebuggerPauseOnDebugger': 'Pause sur une instruction « debugger »',
    'firefox.devtoolsDebuggerPauseOnExceptions': 'Pause sur les exceptions',
    'firefox.devtoolsDebuggerXhrBreakpoints': 'Points d’arrêt XHR',
    'firefox.devtoolsDebuggerEventBreakpoints': 'Points d’arrêt des événements',
    'firefox.devtoolsNetworkAll': 'Tout',
    'firefox.devtoolsNetworkFonts': 'Polices',
    'firefox.devtoolsNetworkImages': 'Images',
    'firefox.devtoolsNetworkMedia': 'Médias',
    'firefox.devtoolsNetworkOther': 'Autre',
    'firefox.devtoolsNetworkColStatus': 'État',
    'firefox.devtoolsNetworkColMethod': 'Méthode',
    'firefox.devtoolsNetworkColDomain': 'Domaine',
    'firefox.devtoolsNetworkColFile': 'Fichier',
    'firefox.devtoolsNetworkColType': 'Type',
    'firefox.devtoolsNetworkColTransfer': 'Transfert',
    'firefox.devtoolsNetworkColSize': 'Taille',
    'firefox.devtoolsNetworkEmpty': 'Aucune requête enregistrée pour le moment. Rechargez la page pour capturer les requêtes réseau.',
    'firefox.devtoolsStyleEditorFilter': 'Filtrer les feuilles...',
    'firefox.devtoolsStyleEditorNoSheets': 'Aucune feuille de style à afficher pour cette page.',
    'firefox.devtoolsStyleEditorEditor': 'Éditeur CSS',
    'firefox.devtoolsStyleEditorSelectSheet': 'Sélectionnez une feuille de style à gauche.',
    'firefox.devtoolsStyleEditorAtRules': 'Règles @',
    'firefox.devtoolsPerfBanner': 'Nouveau : Firefox Profiler est à présent intégré dans les outils de développement.',
    'firefox.devtoolsPerfStartBtn': 'Commencer l’enregistrement ↗',
    'firefox.devtoolsPerfSoon': 'Firefox Profiler : bientôt disponible (ouvre profiler.firefox.com dans un nouvel onglet).',
    'firefox.devtoolsPerfSettings': 'Paramètres',
    'firefox.devtoolsPerfPreset': 'Réglage',
    'firefox.devtoolsPerfPresetValue': 'Développement web',
    'firefox.devtoolsMemoryAllocations': 'Enregistrer les piles d’allocations',
    'firefox.devtoolsMemoryView': 'Afficher',
    'firefox.devtoolsMemoryTreemap': 'Carte proportionnelle',
    'firefox.devtoolsMemoryCapture': 'Capturer un instantané',
    'firefox.devtoolsStorageSession': 'Stockage de session',
    'firefox.devtoolsStorageCache': 'Stockage cache',
    'firefox.devtoolsStorageLocal': 'Stockage local',
    'firefox.devtoolsStorageExpiry': 'Expiration',
    'firefox.devtoolsStorageEmpty': 'Sélectionnez un type de stockage à gauche.',
    'firefox.devtoolsA11ySearchProblems': 'Recherche de problèmes pour :',
    'firefox.devtoolsA11yNone': 'Aucun',
    'firefox.devtoolsA11ySimulate': 'Simuler :',
    'firefox.devtoolsA11yTabOrder': 'Afficher l’ordre de tabulation',
    'firefox.devtoolsA11yChecks': 'Vérifications',
    'firefox.devtoolsA11yNoNode': 'Sélectionnez un nœud pour afficher ses propriétés d’accessibilité.',
    'firefox.devtoolsAppServiceWorkers': 'Service workers',
    'firefox.devtoolsAppManifest': 'Manifeste',
    'firefox.devtoolsAppNoServiceWorker': 'Aucun service worker trouvé.',
    'firefox.devtoolsCloseAria': 'Fermer les outils de développement',
    'firefox.urlbarSearchWith': 'Rechercher avec Google',
    'firefox.urlbarFrequent': 'Sites fréquents',
    'firefox.urlbarEmptyHint': 'Aucun favori ni historique pour le moment.',
};
